// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "testplayground_package",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "testplayground_package",
            targets: ["AppModule"],
            bundleIdentifier: "Uanle.testplayground-package",
            teamIdentifier: "96Z773L75M",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cat),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/apple/example-package-deckofplayingcards", "3.0.5"..<"4.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DeckOfPlayingCards", package: "example-package-deckofplayingcards")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
